# Generated by Django 5.2.1 on 2025-05-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('location', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='crags/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
