# Generated by Django 5.2.1 on 2025-05-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True)),
                ('image_url', models.URLField()),
                ('post_url', models.URLField()),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
