# Generated by Django 5.2.1 on 2025-05-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_instagrampost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbingRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('route_type', models.CharField(choices=[('boulder', 'Boulder'), ('sport', 'Sport'), ('multi', 'Multipitch')], max_length=20)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('difficulty', models.CharField(blank=True, max_length=20)),
                ('crag_name', models.CharField(blank=True, max_length=100)),
                ('node_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CragLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('node_id', models.IntegerField(unique=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('country', models.CharField(blank=True, max_length=100)),
                ('aliases', models.TextField(blank=True)),
            ],
        ),
    ]
