# Generated by Django 5.2.1 on 2025-05-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_climbingroute_craglocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='extracted_route_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='geolocation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
