# Generated by Django 5.2.1 on 2025-05-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_instagrampost_extracted_route_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='shortcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
