# Generated by Django 5.2.1 on 2025-05-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_instagrampost_shortcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampost',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='route_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='post_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='shortcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
