# Generated by Django 5.2.1 on 2025-05-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_instagrampost_geolocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=255)),
                ('route_type', models.CharField(max_length=50)),
                ('shortcode', models.CharField(max_length=50)),
                ('image_url', models.URLField()),
                ('caption', models.TextField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
