# Generated by Django 5.2.1 on 2025-05-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_instaroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='instaroute',
            name='post_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
