# Generated by Django 5.2.1 on 2025-05-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_instaroute_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instaroute',
            name='shortcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
