# Generated by Django 5.2.1 on 2025-06-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_instaroute_shortcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instaroute',
            options={'managed': False},
        ),
    ]
