# Generated by Django 5.2.1 on 2025-06-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_instaroute_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='instaroute',
            table='insta_routes',
        ),
    ]
